# Generated by Django 4.0.4 on 2022-05-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(),
        ),
    ]
