# Generated by Django 4.0.4 on 2022-05-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_donation_is_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='categories',
        ),
    ]
