# Generated by Django 4.0.4 on 2022-05-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donation_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(auto_now=True),
        ),
    ]
